### ISSUE TITLE
Failed to fetch anime list

### ISSUE THREAD

**Issue by brianabdl** [AyraHikari/PyAnimeIndo#1]
Error Message: 

``
Failed to fetch genre list: HTTPSConnectionPool(host='otakudesu.pro', port=443): Max retries exceeded with url: /genre-list/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F3A43FAFD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
``

Possible resolution:
Domain otakudesu had change from [otakudesu.pro](otakudesu.pro) to [otakudesu.lol](otakudesu.lol)

**Comment by AyraHikari** [comment]
Fixed in #2
